### ISSUE TITLE
Find Private Key

### ISSUE THREAD

**Issue by Juventino96** [bakd247/hashAdder#1]
Thank you for your job, but I cannot find the private key with this file "byteAdderOptimized.py" it only found the public key if will add example private key number it will be great.

Best Regards,

**Comment by bakd247** [comment]
I am not finished with the code yet…so it will not find a key yet…you can use the privateKey recovery Tool here:
https://github.com/bakd247/ecdsaKeyFinder
this is the slower version….
I am hoping to be finished with hashAdder this weekend and I will let you know when It is available to use…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: Friday, April 7, 2023 7:39 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [bakd247/hashAdder] Find Private Key (Issue #1)


Thank you for your job, but I cannot find the private key with this file "byteAdderOptimized.py" it only found the public key if will add example private key number it will be great.

Best Regards,

**Comment by bakd247** [comment]
I recently updated the privateKeyFinder.py file so it runs much more efficiently and can accept list sizes up to 00 thousand on both the divisors and the multiple…also the keys per second reading is now correct…
you can use multiple command line windows to use more cores (maximum the number of cores on your machine) to get a much faster search time…
NOTE: keep you list sizes under 100 thousand for best performance…
I will let you know when I am finished with hashAdder…but this tool works the same way…hashAdder is just using multiple cores and disk space to store larger lists…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: Friday, April 7, 2023 7:39 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [bakd247/hashAdder] Find Private Key (Issue #1)


Thank you for your job, but I cannot find the private key with this file "byteAdderOptimized.py" it only found the public key if will add example private key number it will be great.

Best Regards,

**Comment by Juventino96** [comment]
Hi, thank you for your response as I understand new private key finder will be as "binaryAdder.py", "binaryAdderOptomized.py", "byteAdderOptimized.py" with same mechanism, because in that way new program will find very fast, old "privateKeyFinder.py" is very slow for find private key.

**Comment by bakd247** [comment]
Those are the samples file for the newest version that I am still working on…..
I updated privatekeyfinder.py yesterday
Available here:
https://github.com/bakd247/ecdsaKeyFinder
so that it can at least be used while I finish up the new version

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by bakd247** [comment]
You are correct that the newer version will be much faster….I just have to finish multiprocessing and multithreading for arrays in the cpu version of hashAdder, then it will be ready to use….
after that I will be writing a gpu version….but one step at a time…unfortunately I have to work during the days so I can only devote nights and weekends to coding…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Juventino96** [comment]
Hi thank you for your quick response, also I have new request, can you create new file with same mechanism "hashAdder.py" which will generate all possible public keys with multiplication keys example in google bigquery it will great.

**Comment by Juventino96** [comment]
And I am very interested how is success rate of finding the losted private key in new version? Example for one key how many time will be for finding?

Best Regards,
