### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dexizer37** [bakd247/hashAdder#3]
Hi, When will be ready this tools?

**Comment by bakd247** [comment]
I am not sure at the moment...currently I only have my privateKeyFinder.py tool that works to find keys at the moment and only uses linier search. I am currently working on implementing binary search. Once that is done I will add it to hashAdder and hasAdder will be working as a single core single thread version...
I can honestly say that a working version will be available by this summer

**Comment by bakd247** [comment]
I just finished binary search for the privatekeyfindertool so I will be integrating it with hashadder in the next couple of weeks.
