### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by moedacompix** [bakd247/hashAdder#4]
File "D:\hashAdder-main\hashAdder.py", line 4, in <module>
    from binarySearch import binarySearch
ModuleNotFoundError: No module named 'binarySearch'

**Comment by bakd247** [comment]
you have to know how to use python  first!!!

**Comment by bakd247** [comment]
I see what your talking about.....make sure you download all the file...I am going to update them now again

**Comment by bakd247** [comment]
I just updated it and added the binarySearch file...Im sorry I did not see that at first.....I mixed up your post with another as well...sorry about that...thank you for noticing and letting me know...everything should work fine now as long as you have all of the files on the page in the same folder when you run it

**Comment by moedacompix** [comment]
File "D:\hashAdder-main\hashAdder.py", line 38, in <module>
    from byteAdder import multiplyNum
ModuleNotFoundError: No module named 'byteAdder'

**Comment by bakd247** [comment]
thanks again for that....I just changed it....sorry I was testing it with a version that made me not wait as long between instances. 
Everything should work fine now....as far as I know that is the only thing I had changed between the versions

**Comment by moedacompix** [comment]
work.thanks
