### ISSUE TITLE
About saving to file when the key is found

### ISSUE THREAD

**Issue by ben10Talha** [bakd247/hashAdder#8]

**Comment by bakd247** [comment]
I changed version 1.4 to save the key to file if and when it finds one...
Make sure to download 1.4 from the "releases" section using the "sourceCode.zip" file....then extract it prior to running it from the terminal

________________________________
From: ben10Talha ***@***.***>
Sent: Friday, November 8, 2024 2:06 PM
To: bakd247/hashAdder ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bakd247/hashAdder] About saving to file when the key is found (Issue #8)


One important thing about this code: If the computer is shut down or the system is restarted during the search process, all progress will be lost. This is quite risky, especially for long searches. Therefore, I recommend adding a feature that will write temporary data or recorded progress obtained during the search to a file.
