### ISSUE TITLE
I need to make some changes to the code to be able to use this tool as input when part of the key is known.

### ISSUE THREAD

**Issue by Mehmetsait355** [bakd247/hashAdder#9]
![photo_5886213672731264966_y](https://github.com/user-attachments/assets/b5cfa545-6f44-4184-a77a-2cc24ee2253c)
![DYTTRJYTRG](https://github.com/user-attachments/assets/42f6d8f2-8662-411b-9e2c-49c27f2aa81f)
Hello, I have partially mentioned this issue on YouTube. My keys were on the burnt paper in the photo below. Half of it burned in the fire that broke out due to a short circuit in my computer's adapter. The first row is the HEX of my private key, the second is my public key, and the others are my address. Currently, 30 characters are known, half of the 31st character is not fully visible, but it must definitely be a value between 2 and 7. However, to be sure, I want to consider the possibilities of 2, 3, 4, 5, 6, 7. Therefore, I want to set the HashAdder program to search between two known values. In other words, I need to set the code "....0242A(2)000000....." and ".....242a(7)FFFFFF....." like this. Please teach me how to change this code. I would be very happy if you could help me with this. I offer 30% of my balance if my key is found.

**Comment by Mehmetsait355** [comment]
If entering the value range is difficult, then it would be good if I could just enter the first 31 characters. This way, the number of bits that need to be searched would decrease from 136 to 132

**Comment by greenpp88** [comment]
Hello. As far as I know. there is another python program that works for finding partial private key. you can search on github. hope that helps

**Comment by bakd247** [comment]
I will see what I can work out with this this weekend....worst case I will have to make a version of hashadder that uses addition instead of multiplication to allow for prefixes of the private key to be used

**Comment by bakd247** [comment]
can you possibly email me the picture without the marked out part? I would only charge 20% to recover btw...

**Comment by bakd247** [comment]
I am going to be working on a version that allows for partial private key recovery starting in December. Plan on it being finished maybe the end on January or February...
Im not quite sure yet how long it will take because it will contain roughly the same amount of code as hashadder does...

The partial key version will have to use addition and subtraction only...not multiplication and division so there is a bit of tweaking and testing that I will have to do

________________________________

**Comment by Mehmetsait355** [comment]
I will wait patiently and curiously sir. In the meantime, a few things came
to my mind... In the version of Hashadder that does addition and
subtraction instead of multiplication/division, the known key prefix and
possible suffix key will be added to find the key in the unknown part (as
far as I understand). So how will the keys in the unknown part be selected
during this addition and subtraction process?

Also, you said on github that the easycount feature will be added in
hashadder v2, it was mentioned that this will significantly reduce the
worst case scenario... Will this "easycount" feature be available in
Hashadder that does addition and subtraction?


30 Kas 2024 Cmt, saat 21:12 tarihinde Robert Gordon <
***@***.***> şunu yazdı:

**Comment by Mehmetsait355** [comment]
Hello. have a nice day. How are your work on the new program going?


30 Kas 2024 Cmt, saat 21:12 tarihinde Robert Gordon <
***@***.***> şunu yazdı:
